# Generated by Django 4.1.3 on 2022-11-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        default="../media/profile_photo/profile_icon.png",
                        upload_to="profile_photo/%Y/%m/%d",
                        verbose_name="Фото пользователя",
                    ),
                ),
                (
                    "amount_calculations",
                    models.IntegerField(
                        default=0, verbose_name="Количество вычислений"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles",},
        ),
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True,
                        default="image_%y%m%d",
                        max_length=20,
                        verbose_name="name",
                    ),
                ),
                (
                    "calculation_image",
                    models.ImageField(
                        upload_to="calculation_image/%Y/%m/%d",
                        verbose_name="Image for recognition",
                    ),
                ),
                ("info", models.TextField(blank=True, verbose_name="Additional Info")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший вычисление",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calculation",
                "verbose_name_plural": "Calculations",
                "ordering": ["-created_at", "title"],
            },
        ),
    ]
