# Generated by Django 4.1.3 on 2022-12-11 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recognition_app", "0002_alter_calculation_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calculation",
            options={
                "ordering": ["-calculation_name"],
                "verbose_name": "Calculation",
                "verbose_name_plural": "Calculations",
            },
        ),
        migrations.RemoveField(model_name="calculation", name="created_at",),
        migrations.RemoveField(model_name="calculation", name="title",),
        migrations.AddField(
            model_name="calculation",
            name="calculation_name",
            field=models.CharField(
                default="image_1670791368863", max_length=20, verbose_name="image name"
            ),
        ),
        migrations.AddField(
            model_name="calculation",
            name="result",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="prediction by NN"
            ),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user created calculation",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                default="../media/profile_photo/profile_icon.png",
                upload_to="profile_photo/%Y/%m/%d",
                verbose_name="user photo",
            ),
        ),
    ]
